---
- hosts: jenkins
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
  - name: Download Long Term Jenkins release
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: Import jenkins key from url
    ansible.builtin.rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

  - name: yum update
    yum:
      name: '*'
      state: latest

  - name: Install java
    yum:
      name: java-11-openjdk-devel
      state: present

  - name: Install jenkins
    yum:
      name: jenkins
      state: latest

  - name: daemon-reload to pick up config changes
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Start jenkins
    ansible.builtin.systemd:
      name: jenkins
      state: started

  - name: Install git
    yum:
      name: git
      state: latest

  - name: Docker repo
    yum_repository:
      name: docker
      description: repo for docker
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
      gpgcheck: no

  - name: Installing docker
    command:
      cmd: yum install docker-ce --nobest -y

  - name: Starting and enabling docker service
    service:
      name: docker
      state: started
      enabled: yes

  - name: Enabling docker socket permission
    file:
      path: /var/run/docker.sock
      mode: '0666'

  - name: Get the init password Jenkins
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    changed_when: false
    register: password

  - name: Print init password Jenkins
    debug:
      var: password.stdout